---
- name: Get Java tarball
  get_url:
    url: https://download.java.net/java/GA/jdk10/10.0.1/fb4372174a714e6b8c52526dc134031e/10/openjdk-10.0.1_linux-x64_bin.tar.gz
    dest: /etc/open-jdk10.tar.gz

- name: make java 10 directory
  file:
    path: /usr/lib/java10
    state: directory

- name: unpack tarball
  unarchive:
    dest: /usr/lib/java10
    src: /etc/open-jdk10.tar.gz
    remote_src: yes

- name: update alternatives for java
  alternatives:
    name: java
    path: /usr/lib/java10/jdk-10.0.1/bin/java
    link: /usr/bin/java
    priority: 20000

- name: set java home as environment variable
  blockinfile:
    insertafter: EOF
    path: /etc/environment
    block: export JAVA_HOME=/usr/lib/java10/jdk-10.0.1


---
########################################################
# Set up Java 11
########################################################

- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest

- name: Add Oracle Apt Repository
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes

- name: Accept Oracle License
  shell: echo oracle-java11-installer shared/accepted-oracle-license-v1-1 select true | tee /etc/oracle-java-11-licence-acceptance | /usr/bin/debconf-set-selections
  args:
    creates: /etc/oracle-java-11-licence-acceptance

- name: Install Oracle Java 11
  apt: name={{item}} state=latest
  with_items:
    - oracle-java11-installer
    - ca-certificates
    - oracle-java8-set-default

- name: Symlink Default Java
  file: src=/usr/lib/jvm/java-11-oracle dest=/usr/lib/jvm/default-java state=link 

- name: Set JAVA_HOME
  lineinfile: dest=/etc/environment
              regexp=''
              insertafter=EOF
              line="JAVA_HOME=/usr/lib/jvm/default-java"

- name: Verify Java Version
  action: shell /usr/bin/java -version
  register: java
  changed_when: no
  tags:
    - verify

- assert: 
    that: 
      - "'java version' in java.stderr"