---
- name: Get Java tarball
  get_url:
    url: https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
    dest: /etc/openjdk-11.0.2_linux-x64_bin.tar.gz

- name: make java directory
  file:
    path: /usr/lib/java11
    state: directory

- name: unpack tarball
  unarchive:
    dest: /usr/lib/java11
    src: /etc/openjdk-11.0.2_linux-x64_bin.tar.gz
    remote_src: yes

- name: update alternatives for java
  alternatives:
    name: java
    path: /usr/lib/java11/jdk-11.0.2/bin/java
    link: /usr/bin/java
    priority: 20000

- name: set JAVA_HOME as environment variable
  blockinfile:
    insertafter: EOF
    path: /etc/environment
    block: export JAVA_HOME=/usr/lib/java11/jdk-11.0.2
    block: export LS_HOME=/usr/share/logstash
    block: export LS_SETTINGS_DIR=/etc/logstash

- name: Verify Java Version
  action: shell /usr/bin/java -version
  register: java
  changed_when: no
  tags:
    - verify

- assert: 
    that: 
      - "'11.0.2' in java.stderr"