---
- name: Install Filebeat
  apt:
   name: filebeat
   update_cache: yes
- name: Copy Filebeat config
  template: src=filebeat.config.j2 dest=/etc/filebeat/filebeat.yml

- name: Reload systemd config
  systemd: daemon_reload=yes

- name: Starting Filebeat
  service:
   name: filebeat
   state: started
