---
- name: Update repositories cache and install Elasticsearch
  apt:
   name: elasticsearch
   update_cache: yes

- name: Copy Elasticsearch config
  template: src=elasticsearchConf.j2 dest=/etc/elasticsearch/elasticsearch.yml

- name: Reload systemd config
  systemd: daemon_reload=yes
- name: Enable service elasticsearch and ensure it is not masked
  systemd:
    name: elasticsearch
    enabled: yes
    masked: no

- name: Restarting Elasticsearch
  service:
   name: elasticsearch
   state: restarted