---
- name: Adding Kibana APT repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    filename: kibana-7.x.list
    update_cache: yes

- name: Install Kibana
  apt:
    name: kibana
    update_cache: yes

- name: Copy Kibana config
  template: src=kibanaConf.j2 dest=/etc/kibana/kibana.yml

- name: Enabling Kibana service
  systemd:
    name: kibana
    enabled: yes
    daemon_reload: yes

- name: Starting Kibana service
  systemd:
    name: kibana
    state: started
- name: Ensure Kibana is running
  systemd: state=started name=kibana