---
- name: Install logstash from APT repository
  apt: name=logstash state=present force=true update_cache=yes

- name: set JAVA environment variable for logstash
  blockinfile:
    insertafter: EOF
    path: /etc/environment
    block: |
      LS_HOME=/usr/share/logstash
      LS_SETTINGS_DIR=/etc/logstash

- name: Copy logstash configuration files for beats & pfSense
  copy:
    src: "{{ item }}"
    dest: /etc/logstash/conf.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - demo-metrics-pipeline.conf
    - logstash-beats.conf
    - logstash-syslog.conf
    - pfsense-inputs.conf
    - snmp-inputs.conf

- name: Enable Logstash service
  systemd:
    name: logstash
    enabled: yes

- name: Start Logstash service
  systemd:
    name: logstash
    state: started
    daemon_reload: yes