---
# Installing Logstash
- name: Update cache & install logstash from APT repository
  apt: name=logstash state=present force=true update_cache=yes
#--------------------------
## LOGSTASH CONFIGURATION--
#--------------------------
# Configure Beats or any (input source) for logstash pipeline
- name: Configure beats configuration file
  template:
   src=logstash.config.j2
   dest=/etc/logstash/conf.d/logstash.conf
   owner=root
   group=root
   mode=0644
# Configure logstash.yml, if you have specific confg to be used.
- name: Copy logstash configuration files for pfSense
  copy:
    src: "{{ item }}"
    dest: /etc/logstash/conf.d/
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10-inputs.conf
    - 15-firewall.conf
    - 20-others.conf
    - 25-snort.conf
    - 30-geoip.conf
    - 35-dns.conf
    - 40-cleanup.conf
    - 45-outputs.conf

- name: Create patterns directory
  file:
    path: /etc/logstash/conf.d/patterns
    state: directory
    mode: '0744'

- name: Copy pattern file
  copy:
    src: pfelk.grok
    dest: /etc/logstash/conf.d/patterns/pfelk.grok
    owner: root
    group: root
    mode: '0644'
# Configure Elasticsearch output file 55-elasticsearch-output.conf
- name: Configure Elasticsearch output file
  template:
   src=elasticsearch-output.conf.j2
   dest=/etc/logstash/conf.d/55-elasticsearch-output.conf
   owner=root
   group=root
   mode=0644
- name: set JAVA environment variable for logstash
  blockinfile:
    insertafter: EOF
    path: /etc/environment
    block: |
      LS_HOME=/usr/share/logstash
      LS_SETTINGS_DIR=/etc/logstash
# Enable Logstash service
- name: Enable Logstash service
  systemd:
    name: logstash
    enabled: yes
# Start Logstash service
- name: Start Logstash service
  systemd:
    name: logstash
    state: started
    daemon_reload: yes