---
- hosts: elastic1
  remote_user: l00155875
  become: true
  roles:
    - role: pre-requisites
    - role: elastic_stack
    - role: elasticsearch
    - role: kibana
    - role: nginx
    - role: logstash
    - role: filebeat 