---

- name: Install apt-transport-https
  apt: name=apt-transport-https state=present

- name: Install openssl
  apt: name=openssl state=present

- name: Install curl
  apt: name=curl state=present

- name: Install default-jre
  apt: name=default-jre state=present update_cache=yes

- name: Verify java version
  action: shell /usr/bin/java -version
  register: java
  changed_when: no
  tags:
    - verify

- assert: 
    that: 
      - "'{{ java_version }}' in java.stderr"
- debug:
    msg: "Java Version Found {{ java.stderr }}"